# General non-sensitive settings for the server

scopes:
  - https://api.ebay.com/oauth/api_scope/sell.marketing.readonly
  - https://api.ebay.com/oauth/api_scope/sell.inventory.readonly
  - https://api.ebay.com/oauth/api_scope/sell.account.readonly
  - https://api.ebay.com/oauth/api_scope/sell.fulfillment.readonly
  - https://api.ebay.com/oauth/api_scope/sell.analytics.readonly
  - https://api.ebay.com/oauth/api_scope/commerce.identity.readonly
  - https://api.ebay.com/oauth/api_scope/sell.reputation.readonly
  - https://api.ebay.com/oauth/api_scope/commerce.notification.subscription.readonly
  - https://api.ebay.com/oauth/api_scope/sell.stores.readonly

